apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speckle-server
  namespace: {{ .Values.namespace }}
  labels:
{{ include "speckle.labels" . | indent 4 }}
  annotations:
    {{- if .Values.cert_manager_issuer }}
    cert-manager.io/cluster-issuer: {{ .Values.cert_manager_issuer }}
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.org/client-max-body-size: "100m"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  {{- if .Values.cert_manager_issuer }}
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: server-tls
  {{- end }}
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "frontend.name" . }}
            port:
              name: www
      - pathType: Exact
        path: "/(graphql|explorer|(auth/.*)|(objects/.*)|(preview/.*)|(api/.*)|(static/.*))"
        backend:
          service:
            name: {{ include "server.name" . }}
            port:
              name: web
