{{- if (and .Values.ingress.existingCertificate.enabled (or .Values.ingress.certManagerIssuer .Values.cert_manager_issuer)) -}}
{{- fail "Neither 'ingress.certManagerIssuer' or 'cert_manager_issuer' can be defined (non-empty) if you are using an existing certificate ('ingress.existingCertificate.enabled' is true)." -}}
{{- end }}
{{/*
# If using an existing certificate, it does not necessarily imply that it is a self-signed certificate so we should not check that extraCACertificates is also enabled.
{{- if (and .Values.ingress.existingCertificate.enabled (not .Values.extraCACertificates.enabled) )-}}
INCORRECT: {{ fail "'extraCACertificates' must be enabled if you are using an existing certificate ('ingress.existingCertificate.enabled' is true)" }}
{{- end -}}
{{- end -}}
*/}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speckle-server
  namespace: {{ .Values.namespace }}
  labels:
{{ include "speckle.labels" . | indent 4 }}
  annotations:
    {{- if (or .Values.ingress.certManagerIssuer .Values.cert_manager_issuer) }}
    cert-manager.io/cluster-issuer: {{ (empty .Values.ingress.certManagerIssuer) | ternary .Values.cert_manager_issuer .Values.ingress.certManagerIssuer  }}
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ (printf "%dm" (int .Values.file_size_limit_mb)) | quote }}
    nginx.org/client-max-body-size: {{ (printf "%dm" (int .Values.file_size_limit_mb)) | quote }}
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  {{- if (or .Values.cert_manager_issuer .Values.ingress.existingCertificate.enabled) }}
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: server-tls
  {{- end }}
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      {{- if .Values.frontend_2.enabled }}
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: speckle-frontend-2
            port:
              number: 8080
      {{- else }}
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: speckle-frontend
            port:
              number: 8080
      {{- end }}
      - pathType: Exact
        path: "/(graphql|explorer|(auth/.*)|(objects/.*)|(preview/.*)|(api/.*)|(static/.*))"
        backend:
          service:
            name: speckle-server
            port:
              number: 3000
