apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "frontend.labels" . | indent 4 }}
spec:
  selector:
{{ include "frontend.selectorLabels" . | indent 4 }}
  ports:
    - protocol: TCP
      name: www
      port: 8080
      targetPort: www
