{{- if ( or .Values.s3.endpoint .Values.s3.configMap.enabled ) -}}
apiVersion: v1
kind: Service
metadata:
  name: speckle-fileimport-service-metrics
  namespace: {{ .Values.namespace }}
  labels:
{{ include "fileimport_service.labels" . | indent 4 }}
spec:
  selector:
{{ include "fileimport_service.selectorLabels" . | indent 4 }}
  ports:
    - protocol: TCP
      name: web
      port: 9093
      targetPort: metrics
{{- end -}}
